### ISSUE TITLE
Change the error type of Sleep

### ISSUE THREAD

**Issue by canndrew** [rustasync/futures-timer#1]
If I understand correctly, the only time `Sleep::poll` can fail is if the `Sleep` has become invalidated due to a missing global timer runtime or because it's already been polled. Most futures will just panic if they get polled under these sorts of conditions. `Sleep::Error` should be `Void` or, if we want to be able error without panicking, a unit struct like `TimerHasGoneAway`.

*Please* don't just make it `io::Error`. It forces everyone downstream to handle `io::Error`s where they otherwise might not have had to, and where it might not be possible for any errors to really occur at all. In all my recent tokio-based projects one of the first things I write is [a wrapper around `Timeout` which unwraps all the erros](https://github.com/canndrew/crust-futures/blob/master/tokio-utils/src/timeout.rs). I was kinda hoping I would be able to stop doing that with the next version of futures+tokio.

**Comment by yoshuawuyts** [comment]
It's been a while, and we're about to rewrite a large portion of this library to make it compatible with `std::futures`. Thanks for opening this issue, and we'll consider your input in the update!
