### ISSUE TITLE
Change timer concept into a more abstract concept

### ISSUE THREAD

**Issue by harryfei** [rustasync/futures-timer#3]
Currently, this crate use `Timer` as the scheduler for `Delay` and `Interval`.
Shall we make the `Timer` more abstract to make it possible to implement more scheduler.
eg.
 * Tokio based timer scheduler
 * Fake timer scheduler for testing.

**Comment by alexcrichton** [comment]
Certainly, I'd be down for this! I'm not entirely sure what it would look like but something along these lines seems plausible!

**Comment by yoshuawuyts** [comment]
Thanks for opening this issue! -- we're making this possible in https://github.com/rustasync/runtime/pull/36! :sparkles:
