### ISSUE TITLE
difference to tokio-timer?

### ISSUE THREAD

**Issue by flosse** [rustasync/futures-timer#9]
What's the difference of `futures-timer` to `tokio-timer`?

**Comment by alexcrichton** [comment]
This crate doesn't currently depend on `tokio`, but I don't have a lot of time to maintain it unfortunately. There may be implementation differences as well, I'm not too familiar with `tokio-timer`

**Comment by ArtemGr** [comment]
The later tokio-timer release (0.2) depends on the Tokio runtime.
"*Using the timer API requires a timer instance to be running. The Tokio runtime takes care of all that setup for you.*" - https://tokio.rs/blog/2018-03-timers/
If one tries to use the tokio-timer outside of the Tokio runtime the timers simply don't fire (IIRC).
